language: java

addons:
  apt:
    packages:
    - graphviz
    - xmlstarlet

jdk:
- oraclejdk11

install: skip

script:
- wget -O settings.xml https://raw.githubusercontent.com/pousse-cafe/pousse-cafe-deploy/master/snapshot_release_settings.xml
- if ./can_auto_deploy.sh  ; then mvn deploy -B -U --settings settings.xml; else mvn verify -B -U; fi

env:
  global:
  - secure: tuw10Ikq2lXnljeoClje8w/SADU4Ann6bLxUs7Ix2PH9MgR+d+/efZsaZRWki2hGBzxxVChsxUIzWitFbwVvzqC7PPUxlAKAPwuF7F+ODz84Dzduc7MABwn28CeWxSpaw/mZoeLV7Xtt2QtMUBKBZc4Afnk8dTD1u4DjzmuEwp9TbwHcq9lQD/FJaV0OzZN0e//FXjz+WfbiGQ7CLgLBpzIjfdSYemEJnWga6jvgzI3l66vwpHolcNhWN2fz6yJeOWVXNioGWI90u756yxK9n3rf4HjsmuGkHFQGJ/5Cr2DZe4qtJBFQT6+r1yhUAFj8XljDTM483GcJ9b3a+T4TLDPfF7hGXuTn3TsPPhmEppuLPD4YFf6y4oT0i4aYe/LYrosHcXjykM4XZoeOgyorVJiCKDLu+zJ6tlwHGbS/ajVkYax719an188cq26tiMU9+R5kXpbDfMkalCckumBsTPU8QbEOaum5kSPKm6DlcJ24wKHxJSUz2yDSdIvjkI+9G4hSwoRFboqAl9yO41ppmFZ6nsqkvaLNtw6/aDdHUe+wlv7m4pwR2HT5ozpNu3+7cUa+Nkhuyt9j39556fxJyjXIEMgRKM4tAhAGtZ8VoCR6MXyxEOdL800X2Y+XbTSmvkIXxtHWmg6ExADX6AeF8N9r+JvE4ZK7hdCF1gMALh8=
  - secure: EqFny+BnTiC5jSnyeVxHxvFNklJRz16/o3vCos9hGM7GvIrdXA/YhCoytKJkLILayLVCWjSBp5eMlkomYNeNd5rNoF6RjwYiMZPonpH0v7hy69yYE0UxO+ioComPM3pW7eyQzFUGId0N6fWolW8c0Vg12kxk3VEg/PlWH56g0KYEK1t7C+dHQP5hQAt3PIsVfPFUCZQWgGByVcXb2gJEGDpEvb6SAGQYRBfcwieAYWqAPyNoBeVJB6orHVHIG0KxJg6amYb7qmol8nxbdo8v1A848bM74fo2PY2JgDWdrtWfPCY6/0c1x+OebPWKb6aBmpNIYg+4vWWIpzUVegdodctZbGW2eFl+2fAw+xMAIOfRoP0D1J71z814EeJzzYwAbdsxXv2rQndD05FE0O28/836SdZs1mv5q9xrbSHoLXAnjD6TaUjO1ZKBH3NfmJQtGb9viDZ8iEze25uuPDWqH1Im+d93108FTyLVY/q3tuXFh0FgwVuPacCh2tg0c70aEsVSmqf4Ju2u/UF04IA+dX7Ul0hW1H1uw6K4zghfSsnpzlDmKFxrMDOrbyJidUOseKgJs/7vFMUdwLE9s2cOm25iSVny2jerUIkiNnklNkGx/jjmiIckLW5wVjDR0Xuk7dGURDiDc20VgDNQ7X/W+8OEXbFgvHN/s614+QHiCAc=
